version: '3.8'

services:
  hackernews-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackernews-mcp-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HACKERNEWS_API_BASE_URL=https://hacker-news.firebaseio.com/v0
      - HACKERNEWS_API_TIMEOUT=10000
      - HACKERNEWS_API_RETRY_ATTEMPTS=3
      - HACKERNEWS_API_RETRY_DELAY=1000
      - HACKERNEWS_CACHE_DEFAULT_TTL=300000
      - HACKERNEWS_CACHE_MAX_SIZE=1000
      - HACKERNEWS_CACHE_CLEANUP_INTERVAL=600000
      - HACKERNEWS_LOG_LEVEL=info
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge 